version: '3.7'
services:
  pg:
    image: postgres:9.6.20-alpine
    shm_size: '1G'
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=10'
      - '-c'
      - 'effective_cache_size=2304MB'
      - '-c'
      - 'shared_buffers=768MB'
      - '-c'
      - 'fsync=off'
      - '-c'
      - 'synchronous_commit=off'
      - '-c'
      - 'full_page_writes=off'
      - '-c'
      - 'autovacuum=off'
      - '-c'
      - 'work_mem=32MB'
      - '-c'
      - 'wal_level=minimal'
      - '-c'
      - 'max_wal_senders=0'
      - '-c'
      - 'wal_buffers=-1'
      - '-c'
      - 'max_worker_processes=3'
      - '-c'
      - 'max_parallel_workers_per_gather=2'
      - '-c'
      - 'maintenance_work_mem=2304MB'
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: "${PG_STAGING_USER:-example}"
      POSTGRES_PASSWORD: "${PG_STAGING_PASS:-example}"
      POSTGRES_DB: "${PG_STAGING_DB:-example_development}"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
